### ISSUE TITLE
error message about promise && connection

### ISSUE THREAD

**Issue by sandybemonkey** [koajs/kick-off-koa#20]
Hi when i verify my answer for routing exercice i have this error:

/home/mnk/Documents/dev/nodeDev/koa/node_modules/koa/node_modules/co/index.js:88
    if (ret.done) return Promise.resolve(ret.value);
                         ^
ReferenceError: Promise is not defined
    at next (/home/mnk/Documents/dev/nodeDev/koa/node_modules/koa/node_modules/co/index.js:88:26)
    at onFulfilled (/home/mnk/Documents/dev/nodeDev/koa/node_modules/koa/node_modules/co/index.js:59:12)
    at Object.co (/home/mnk/Documents/dev/nodeDev/koa/node_modules/koa/node_modules/co/index.js:44:10)
    at Object.<anonymous> (/home/mnk/Documents/dev/nodeDev/koa/node_modules/koa/node_modules/co/index.js:28:15)
    at Server.<anonymous> (/home/mnk/Documents/dev/nodeDev/koa/node_modules/koa/lib/application.js:123:8)
    at Server.EventEmitter.emit (events.js:107:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:504:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:357:22)
    at Socket.EventEmitter.emit (events.js:104:17)
✗ Error connecting to submission server(http://localhost:45317/404), options: {"timeout":5000,"maxRedirects":10}. Error: connect ECONNREFUSED
    at exports._errnoException (util.js:745:11)
    at Object.afterConnect [as oncomplete](net.js:995:19)

**Comment by sandybemonkey** [comment]
sorry i was in a long trip..thanks for your answer!!
