### ISSUE TITLE
Navigating to `Choose Language` and then choosing an exercise crashes

### ISSUE THREAD

**Issue by hivinay** [koajs/kick-off-koa#32]
Navigating to `Choose Language` and either choosing a language or `Cancel`, then at the main menu choosing an exercise, results in the following error:

```
events.js:72
      listeners[i].call(self);
                  ^
TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:72:19)
    at Stream.emit (events.js:166:7)
    at Stream.Charm.end (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/workshopper/node_modules/terminal-menu/node_modules/charm/index.js:107:10)
    at Menu.close (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/workshopper/node_modules/terminal-menu/index.js:126:16)
    at Menu.<anonymous> (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/workshopper/menu.js:75:10)
    at emitTwo (events.js:92:20)
    at Menu.emit (events.js:172:7)
    at Menu.ondata [as _ondata] (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/workshopper/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/workshopper/node_modules/terminal-menu/index.js:50:18)
    at DestroyableTransform.Transform._read (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (~/Documents/npm-global/lib/node_modules/kick-off-koa/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

**Comment by hemanth** [comment]
Not able to reproduce, can you tell me more details of the `env` you are on, the version of `kick-off-koa` ?

**Comment by hivinay** [comment]
Upon further investigation the issue is only present on iojs 2.4.0 but it works fine on node 0.12.7. Therefore I'm not sure where the issue lies. In any case I am on `kick-off-koa` version 2.0.0.

```
─┬ kick-off-koa@2.0.0
  ├─┬ colors-tmpl@1.0.0
  │ └── colors@1.0.3
  ├─┬ combined-stream@0.0.7
  │ └── delayed-stream@0.0.5
  ├── freeport@1.0.5
  ├── pedding@1.0.0
  ├─┬ through2@0.6.5
  │ ├─┬ readable-stream@1.0.33
  │ │ ├── core-util-is@1.0.1
  │ │ ├── inherits@2.0.1
  │ │ ├── isarray@0.0.1
  │ │ └── string_decoder@0.10.31
  │ └── xtend@4.0.0
  ├─┬ urllib@2.3.9
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├── default-user-agent@0.0.1
  │ ├─┬ digest-header@0.0.1
  │ │ └─┬ utility@0.1.11
  │ │   └── address@0.0.3
  │ ├─┬ humanize-ms@1.0.1
  │ │ └── ms@0.6.2
  │ ├── iconv-lite@0.4.11
  │ ├── media-typer@0.3.0
  │ ├── native-or-bluebird@1.2.0
  │ └── statuses@1.2.1
  ├─┬ workshopper@2.7.0
  │ ├─┬ chalk@0.4.0
  │ │ ├── ansi-styles@1.0.0
  │ │ ├── has-color@0.1.7
  │ │ └── strip-ansi@0.1.1
  │ ├─┬ colors-tmpl@0.1.1
  │ │ └── colors@0.6.2
  │ ├─┬ i18n-core@1.3.3
  │ │ ├── mustache@0.8.2
  │ │ └── sprintf@0.1.5
  │ ├── map-async@0.1.1
  │ ├── mkdirp@0.3.5
  │ ├─┬ msee@0.1.1
  │ │ ├─┬ cardinal@0.4.4
  │ │ │ ├── ansicolors@0.2.1
  │ │ │ └─┬ redeyed@0.4.4
  │ │ │   └── esprima@1.0.4
  │ │ ├── marked@0.3.3
  │ │ ├─┬ nopt@2.1.2
  │ │ │ └── abbrev@1.0.7
  │ │ └─┬ xtend@2.1.2
  │ │   └── object-keys@0.4.0
  │ ├─┬ optimist@0.6.1
  │ │ ├── minimist@0.0.10
  │ │ └── wordwrap@0.0.3
  │ ├─┬ terminal-menu@2.1.1
  │ │ ├── charm@0.1.2
  │ │ ├─┬ duplexer2@0.0.2
  │ │ │ └─┬ readable-stream@1.1.13
  │ │ │   ├── core-util-is@1.0.1
  │ │ │   ├── isarray@0.0.1
  │ │ │   └── string_decoder@0.10.31
  │ │ ├── inherits@2.0.1
  │ │ └─┬ resumer@0.0.0
  │ │   └── through@2.3.8
  │ ├── visualwidth@0.0.1
  │ └── xtend@3.0.0
  └─┬ workshopper-exercise@2.4.0
    ├── after@0.8.1
    ├─┬ chalk@0.4.0
    │ ├── ansi-styles@1.0.0
    │ ├── has-color@0.1.7
    │ └── strip-ansi@0.1.1
    ├─┬ i18n-core@1.3.3
    │ ├── mustache@0.8.2
    │ └── sprintf@0.1.5
    ├─┬ split@0.3.3
    │ └── through@2.3.8
    ├─┬ through2@0.4.2
    │ └─┬ readable-stream@1.0.33
    │   ├── core-util-is@1.0.1
    │   ├── inherits@2.0.1
    │   ├── isarray@0.0.1
    │   └── string_decoder@0.10.31
    ├─┬ tuple-stream@0.0.2
    │ └── through@2.3.8
    ├── visualwidth@0.0.1
    └─┬ xtend@2.1.2
      └── object-keys@0.4.0
```

**Comment by hemanth** [comment]
Oh OK, it's better we debug further and report it on `iojs`, thanks.
