### ISSUE TITLE
Can't verify first exercise

### ISSUE THREAD

**Issue by nikolaykletskin** [koajs/kick-off-koa#42]
I can't verify first exercise, even if I copy it's source from this repository.

After I try "kick-off-koa verify ex1.js" I get following error:

/Users/nikolaykletskin/projects/nodeschool/koa/node_modules/koa/node_modules/composition/node_modules/any-promise/register.js:61
    throw new Error('Cannot find any-promise implementation nor'+
          ^
Error: Cannot find any-promise implementation nor global.Promise. You must install polyfill or call require("any-promise/register") with your preferred implementation, e.g. require("any-promise/register")("bluebird") on application load prior to any require("any-promise").
    at register (/Users/nikolaykletskin/projects/nodeschool/koa/node_modules/koa/node_modules/composition/node_modules/any-promise/register.js:61:11)
    at Object.<anonymous> (/Users/nikolaykletskin/projects/nodeschool/koa/node_modules/koa/node_modules/composition/node_modules/any-promise/index.js:1:101)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/Users/nikolaykletskin/projects/nodeschool/koa/node_modules/koa/node_modules/composition/index.js:2:15)
    at Module._compile (module.js:449:26)
✗ Error connecting to submission server (http://localhost:51186/hello), options: {"timeout":5000,"maxRedirects":10}. Error: connect ECONNREFUSED
    at exports._errnoException (util.js:742:11)
    at Object.afterConnect [as oncomplete] (net.js:989:19)

**Comment by dead-horse** [comment]
please use node v4.x

**Comment by nikolaykletskin** [comment]
Thank you. Works well!
