### ISSUE TITLE
error occurs when selecting `CHOOSE LANGUAGE` again.

### ISSUE THREAD

**Issue by arbipher** [koajs/kick-off-koa#43]
I find it reports error when selecting `CHOOSE LANGUAGE` again.
# steps
1. `$> kick-off-koa`
2. select `CHOOSE LANGUAGE` then select `French` (or `English`)
3. select `CHOOSE LANGUAGE`
# error notes

```
events.js:72
      listeners[i].call(self);
                  ^

TypeError: Cannot read property 'call' of undefined
    at emitNone (events.js:72:19)
    at Stream.emit (events.js:166:7)
    at Stream.Charm.end (/usr/local/lib/node_modules/kick-off-koa/node_modules/charm/index.js:107:10)
    at Menu.close (/usr/local/lib/node_modules/kick-off-koa/node_modules/terminal-menu/index.js:126:16)
    at Menu.<anonymous> (/usr/local/lib/node_modules/kick-off-koa/node_modules/workshopper/menu.js:75:10)
    at emitTwo (events.js:92:20)
    at Menu.emit (events.js:172:7)
    at Menu.ondata [as _ondata] (/usr/local/lib/node_modules/kick-off-koa/node_modules/terminal-menu/index.js:215:18)
    at DestroyableTransform._transform (/usr/local/lib/node_modules/kick-off-koa/node_modules/terminal-menu/index.js:50:18)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/kick-off-koa/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/kick-off-koa/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/kick-off-koa/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/kick-off-koa/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/kick-off-koa/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

`node` version is `v5.3.0`

**Comment by wangxiaose** [comment]
kick-off-koa

**Comment by wangxiaose** [comment]
kick-off-koa

**Comment by hemanth** [comment]
`v5.3.0` works fine for me.
