### ISSUE TITLE
Error connecting to submission server, lesson 2 routing.

### ISSUE THREAD

**Issue by ApacheTyler** [koajs/kick-off-koa#53]
After copying and pasting the solution, I still get the following error:

```javascript
Server listening at port 63797
✗ Error connecting to submission server (http://localhost:63797/), options: {"requestUrls":["http://localhost:63797/"],"timeout":[5000,5000],"maxRedirects":10}. ConnectionTimeoutError: Connect timeout for 5000ms, GET http://localhost:63797/ -2 (connected: false, keepalive socket: false)
headers: {}
    at Timeout._onTimeout (/usr/local/lib/node_modules/kick-off-koa/node_modules/urllib/lib/urllib.js:701:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

Code:
```javascript
var koa = require('koa');

var app = koa();

app.use(function* (next) {
  if (this.path !== '/') {
    return yield next;
  }

  this.body = 'hello koa';
});

app.use(function* (next) {
  if (this.path !== '/404') {
    return yield next;
  }

  this.body = 'page not found';
});

app.use(function* (next) {
  if (this.path !== '/500') {
    return yield next;
  }

  this.body = 'internal server error';
});

var port = process.argv[2];

app.listen(port, function () {
    console.log('Server listening at port ' + port);
});
```

Node Version:
7.1.0

OS:
10.12.1

Kick off koa:
kick-off-koa@2.0.0

This solution works as expected if visiting from the browser.

**Comment by hemanth** [comment]
> This solution works as expected if visiting from the browser. 

On `http://localhost:63797/` ?

**Comment by ApacheTyler** [comment]
That was correct.

After trying again this morning, I am now getting the expected output when running 'verify'. There must be something odd on my end.
